### ISSUE TITLE
Script works but metasploit gets corrupted

### ISSUE THREAD

**Issue by hackerb49** [remo7777/Termux-Apktool#2]
I think thers some problems
 with apk.rb, because when i bind a paylod to apk and type tey to open msfconsole, it won't load
It says some error in payload_generator.rb

**Comment by remo7777** [comment]
are you using metasploit from unstable-repo ??

**Comment by remo7777** [comment]
or type command 
`which msfconsole`

and me that output

**Comment by remo7777** [comment]
> I think thers some problems
> with apk.rb, because when i bind a paylod to apk and type tey to open msfconsole, it won't load
> It says some error in payload_generator.rb

apk.rb is use on original.apk payload bind
you are talking about raw payload....
if you are using `msfvenom -x` option it ll for orignal apk and it ll auto signed your payload apk so do not again sign with you payload
